name: bloc_boilerplate
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  cupertino_icons: ^1.0.3
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.4
  font_awesome_flutter: ^10.12.0
  device_info_plus: ^10.0.0
  intl: ^0.20.2
  firebase_messaging: ^16.1.1
  rxdart: ^0.28.0
  intro_views_flutter: ^3.2.0
  dio: ^5.9.1
  flutter_secure_storage: ^10.0.0
  local_auth: ^3.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/
    - assets/locale/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf
  uses-material-design: true